"""Added favorite and templates

Revision ID: d3655bb2f099
Revises: 364a9318ef10
Create Date: 2023-04-10 06:11:21.320081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3655bb2f099'
down_revision = '364a9318ef10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('favorites',
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['resume.resume_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hr_id'], ['users.user_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('msg_templates')
    # ### end Alembic commands ###
